import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styled from 'styled-components';

const Container = styled.div`
  display:block;
  width:100%;
  height:100vh;
  background-color:gray;
`

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Find auto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <h1>Find Auto</h1>
       <p>Lista aut</p>
       <Container>

       </Container>
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
