import Head from 'next/head'
import {default as NextImage} from 'next/image'
import styles from '../styles/Home.module.css'
import styled from 'styled-components';

const Container = styled.div`
  display:flex;
  justify-content:center;
  width:100%;
  height:auto;
  background-color:gray;
`

const Image = styled.img`
  width:100%;
  height:auto;
`

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Find auto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <h1>Find Auto</h1>
       {/* <p>Lista aut</p> */}
       <h3>Audi A3</h3>
       <h5>2018, 63 132 km, Benzyna, Kompakt </h5>
       <Container>
        <Image src="/image1080x720.webp"/>
       </Container>
       <Container>
        <Image src="/image-map.png"/>
       </Container>
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
